pool:
  vmImage: ubuntu-latest

steps:
- script: |
    curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
  displayName: 'Install Postman CLI'

- task: CmdLine@2
  displayName: 'Run automated API tests using Postman CLI'
  inputs:
    script: |
        postman login --with-api-key PMAK-63977a9bc6822b1cad0714d7-f196bb52326b4f3459a14cbf2cc78913f3
        # Run your collection using Postman CLI
        postman collection run "5260842-34cc7875-b21d-474a-8d8f-48154d77672c" -e "5260842-6af82ab9-5541-46d7-8ee7-9f592f0ecb97"